# Generated by Django 4.1.5 on 2023-01-19 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='posts/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='post.tag'),
        ),
    ]
